### ISSUE TITLE
working with a button across multiple views

### ISSUE THREAD

**Issue by hsavit1** [DavdRoman/Popsicle#13]
hey,

I have a button that I anchor to a corner on the first page, and it stays static across 3 separate page views. The button gets anchored fantastically, however it removes itself as a target in the second and third pages. Any idea as to how I can keep it as a functional button?

Thanks!

**Comment by Dromaguirre** [comment]
Hi.

I'd need more info to evaluate your issue. Are you using DRPageScrollView? If so, did you enable page reuse?

**Comment by Dromaguirre** [comment]
Hey @hsavit1 did you finally get around with this issue?

**Comment by hsavit1** [comment]
Yea I never figured it out actually.

The Button loses its functionality on the second and third pages of the
view pager. Will keep you posted if I come up with something

On Monday, June 8, 2015, David Román <notifications@github.com> wrote:

> Hey @hsavit1 <https://github.com/hsavit1> did you finally get around with
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dromaguirre/Popsicle/issues/13#issuecomment-109955630>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Dromaguirre** [comment]
@hsavit1 

Oh my. I just came up with what that's about. Since the page view where the button is contained is out of bounds but the button is still visible, it won't receive touch events. It's a default behavior every UIView component has: they ignore touch events when they're out of bounds from their parent superviews.

Check out this official document from Apple where they explain how to get around it: https://developer.apple.com/library/ios/qa/qa2013/qa1812.html

**Comment by hsavit1** [comment]
hey, forgot to respond to this

looks neat! will check out
